import { Card } from '@/types/vsa-royale'

export const VSA_CARDS: Card[] = [
  // Legendary Cards - Executive Board
  {
    id: 'president',
    name: 'VSA President',
    type: 'member',
    rarity: 'legendary',
    cost: 8,
    hp: 2400,
    damage: 280,
    attackSpeed: 1.5,
    range: 5,
    speed: 1,
    description: 'The leader of VSA with area damage and leadership aura',
    ability: 'Boosts nearby units attack speed by 35%',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'vice_president',
    name: 'Vice President',
    type: 'member',
    rarity: 'legendary',
    cost: 7,
    hp: 3200,
    damage: 220,
    attackSpeed: 1.8,
    range: 1,
    speed: 0.8,
    description: 'Tank unit with high HP and shield ability',
    ability: 'Generates shield for nearby units',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'treasurer',
    name: 'Treasurer',
    type: 'member',
    rarity: 'legendary',
    cost: 6,
    hp: 1200,
    damage: 150,
    attackSpeed: 1.2,
    range: 4,
    speed: 1.2,
    description: 'Manages resources efficiently',
    ability: 'Generates +1 eggroll every 10 seconds',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'secretary',
    name: 'Secretary',
    type: 'member',
    rarity: 'legendary',
    cost: 5,
    hp: 1000,
    damage: 180,
    attackSpeed: 0.8,
    range: 6,
    speed: 1.5,
    description: 'Fast attack speed with documentation projectiles',
    ability: 'Attacks hit multiple targets',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },

  // Epic Cards - Committee Chairs
  {
    id: 'cultural_chair',
    name: 'Cultural Chair',
    type: 'member',
    rarity: 'epic',
    cost: 5,
    hp: 800,
    damage: 120,
    attackSpeed: 1.0,
    range: 3,
    speed: 1.2,
    description: 'Spawns traditional dancers',
    ability: 'Spawns 3 mini dancers on death',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'social_chair',
    name: 'Social Chair',
    type: 'member',
    rarity: 'epic',
    cost: 4,
    hp: 900,
    damage: 140,
    attackSpeed: 1.3,
    range: 2,
    speed: 1.4,
    description: 'Boosts allied unit speed',
    ability: 'Party aura: +25% movement speed',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'pr_chair',
    name: 'PR Chair',
    type: 'member',
    rarity: 'epic',
    cost: 5,
    hp: 700,
    damage: 200,
    attackSpeed: 2.0,
    range: 8,
    speed: 1.0,
    description: 'Long-range camera flash attacks',
    ability: 'Stuns enemies for 0.5 seconds',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'fundraising_chair',
    name: 'Fundraising Chair',
    type: 'member',
    rarity: 'epic',
    cost: 6,
    hp: 1100,
    damage: 160,
    attackSpeed: 1.5,
    range: 4,
    speed: 1.1,
    description: 'Converts enemy units',
    ability: 'Has 30% chance to convert low HP enemies',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },

  // Rare Cards
  {
    id: 'senior_member',
    name: 'Senior Member',
    type: 'member',
    rarity: 'rare',
    cost: 4,
    hp: 800,
    damage: 140,
    attackSpeed: 1.4,
    range: 3,
    speed: 1.2,
    description: 'Experienced and balanced fighter',
    ability: 'None',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'junior_member',
    name: 'Junior Member',
    type: 'member',
    rarity: 'rare',
    cost: 3,
    hp: 600,
    damage: 100,
    attackSpeed: 1.2,
    range: 2,
    speed: 1.4,
    description: 'Enthusiastic and quick',
    ability: 'None',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'alumni_supporter',
    name: 'Alumni Supporter',
    type: 'member',
    rarity: 'rare',
    cost: 5,
    hp: 1200,
    damage: 180,
    attackSpeed: 2.0,
    range: 4,
    speed: 0.8,
    description: 'Powerful but slow',
    ability: 'None',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },

  // Common Cards
  {
    id: 'freshman_member',
    name: 'Freshman Member',
    type: 'member',
    rarity: 'common',
    cost: 2,
    hp: 400,
    damage: 80,
    attackSpeed: 1.0,
    range: 2,
    speed: 1.3,
    description: 'New but eager to help',
    ability: 'None',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'volunteer',
    name: 'Volunteer',
    type: 'member',
    rarity: 'common',
    cost: 1,
    hp: 250,
    damage: 60,
    attackSpeed: 0.8,
    range: 1,
    speed: 1.5,
    description: 'Quick and cheap unit',
    ability: 'None',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'exchange_student',
    name: 'Exchange Student',
    type: 'member',
    rarity: 'common',
    cost: 3,
    hp: 500,
    damage: 90,
    attackSpeed: 1.1,
    range: 3,
    speed: 1.2,
    description: 'Random ability each deployment',
    ability: 'Random buff on spawn',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },

  // Spell Cards
  {
    id: 'tet_firecracker',
    name: 'Tết Firecracker',
    type: 'spell',
    rarity: 'common',
    cost: 3,
    description: 'Area damage spell',
    ability: 'Deals 300 damage in area',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'pho_power',
    name: 'Phở Power-up',
    type: 'spell',
    rarity: 'rare',
    cost: 4,
    description: 'Heal all friendly units',
    ability: 'Heals 400 HP to all allies',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'banh_mi_barrage',
    name: 'Bánh Mì Barrage',
    type: 'spell',
    rarity: 'epic',
    cost: 5,
    description: 'Projectile rain from above',
    ability: 'Deals 150 damage x 8 projectiles',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'dragon_dance',
    name: 'Dragon Dance',
    type: 'spell',
    rarity: 'legendary',
    cost: 6,
    description: 'Temporary invincibility shield',
    ability: 'All units invincible for 2 seconds',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
  {
    id: 'spring_roll_rush',
    name: 'Spring Roll Rush',
    type: 'spell',
    rarity: 'common',
    cost: 2,
    description: 'Speed boost for units',
    ability: '+50% speed for 5 seconds',
    imageUrl: '/images/dong/dongKawaii.JPG',
  },
]

export function getCardById(id: string): Card | undefined {
  return VSA_CARDS.find((card) => card.id === id)
}

export function getCardsByRarity(rarity: Card['rarity']): Card[] {
  return VSA_CARDS.filter((card) => card.rarity === rarity)
}

export function getStarterDeck(): string[] {
  return [
    'freshman_member',
    'volunteer',
    'junior_member',
    'tet_firecracker',
    'spring_roll_rush',
    'exchange_student',
    'senior_member',
    'pho_power',
  ]
}
